--Ex. 1 
CREATE TABLESPACE AEBD_TABLES 
    DATAFILE 
        '\u01\app\oracle\oradata\orcl12\orcl\AEBD_TABLES_01.DBF' SIZE 104857600;
--Ex. 2    
CREATE TEMPORARY TABLESPACE AEBD_TEMP 
    TEMPFILE 
        '\u01\app\oracle\oradata\orcl12\orcl\AEBD_TEMP_01.DBF' SIZE 52428800 AUTOEXTEND ON NEXT 104857600 MAXSIZE 34359721984 
    EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1048576;

-- Ex. 4
CREATE USER cisco IDENTIFIED BY pass  
DEFAULT TABLESPACE AEBD_TABLES
TEMPORARY TABLESPACE AEBD_TEMP
PASSWORD EXPIRE ;

ALTER USER cisco QUOTA UNLIMITED ON AEBD_TABLES;

-- Ex.5
GRANT "DBA" TO cisco ;

GRANT CREATE SESSION TO cisco ;
GRANT CREATE TABLE TO cisco ;

-- Ex.7
connect cisco/pass;

show user;

-- Ex 9 

  CREATE TABLE PATROCINADOR
   (	ID_PATROCINADOR NUMBER NOT NULL ENABLE, 
	NOME VARCHAR2(200 BYTE), 
	MONTANTE NUMBER, 
    CONSTRAINT ID_PTROCINADOR PRIMARY KEY (I_PATROCINADOR)
   ) ;







